version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/rails"
    environment:
      RAILS_ENV: "production"
      RAILS_MASTER_KEY: "2a326bf4bb17d305c13437dd403a833d"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/neverends_production"  # Указываем правильные параметры подключения
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neverends_production
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata: