default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: db  # Имя контейнера с базой данных (по умолчанию в docker-compose.yml)

development:
  <<: *default
  database: neverends_development

test:
  <<: *default
  database: neverends_test

production:
  <<: *default
  database: neverends_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
